# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Make requirements.txt
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Source venv
      run: |
        source venv/Scripts/activate
    - name: Make requirements.txt
      run: |
        pip freeze > requirements.txt
